organization: tegioz-tests
teams:
  - name: team1
    maintainers:
      - cynthia-sg
    members:
      - Clomonitor1
      - Clomonitor2
  - name: team2
    maintainers:
      - cynthia-sg
    members:
      - tegioz
  - name: team3
    maintainers:
      - cynthia-sg
    members: []
repositories:
  - name: .clowarden
    teams:
      team1: admin
    external_collaborators:
      tegioz: admin
    visibility: private
  - name: tests
    external-collaborators:
      cynthia-sg: write
    visibility: public
